# Generated by Django 5.2.16 on 2026-07-20 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Used as the filter value, e.g. 'green'", unique=True)),
                ('label', models.CharField(help_text="Shown on the filter button, e.g. 'Green Tech'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Project categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('badge_text', models.CharField(help_text="Small badge label, e.g. 'Circular Economy'", max_length=50)),
                ('badge_color', models.CharField(choices=[('green', 'Green'), ('blue', 'Blue'), ('dark-green', 'Dark Green')], default='green', max_length=20)),
                ('tags', models.CharField(help_text="Comma-separated, e.g. 'Recycling, Green Manufacturing'", max_length=200)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in the Featured Project highlight instead of the grid.')),
                ('impact_summary', models.CharField(blank=True, help_text="Only used when featured, e.g. '35 enterprises created, 1,200+ jobs generated, 15+ communities reached.'", max_length=200)),
                ('stat_1_number', models.CharField(blank=True, help_text="e.g. '35' (featured only)", max_length=20)),
                ('stat_1_label', models.CharField(blank=True, help_text="e.g. 'Enterprises' (featured only)", max_length=50)),
                ('stat_2_number', models.CharField(blank=True, max_length=20)),
                ('stat_2_label', models.CharField(blank=True, max_length=50)),
                ('stat_3_number', models.CharField(blank=True, max_length=20)),
                ('stat_3_label', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.projectcategory')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
