# Generated by Django 5.2.16 on 2026-07-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_seed_partner_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnershipOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Used as the value in the partnership type dropdown, e.g. 'funding'", unique=True)),
                ('icon_class', models.CharField(help_text="Font Awesome class, e.g. 'fas fa-hand-holding-dollar'", max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Partnership opportunities',
                'ordering': ['order', 'id'],
            },
        ),
    ]
